version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      # Add your environment variables here
      # - NEXT_PUBLIC_GA_TRACKING_ID=your-ga-id
      # - NEXT_PUBLIC_PLAUSIBLE_DOMAIN=your-domain.com
    restart: unless-stopped
    container_name: hypnotherapy-website
